rewards:
  1:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'
  2:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'
  3:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'
  4:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'
  5:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'
  6:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'
  7:
    default:
      commands:
        - 'give vote 1 %player%'
    vip:
      commands:
        - 'broadcast naber'
    megavip:
      commands:
        - 'give vote 1 %player%'
    ultravip:
      commands:
        - 'give vote 1 %player%'
    spearvip:
      commands:
        - 'give vote 1 %player%'
    spearvip+:
      commands:
        - 'give vote 1 %player%'



gui:
  1:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "#FFC312VIP &8- &71 Vote Kasası"
      - "#FFC312VIP &8- &720 dk Fly"
      - "#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"
  2:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "#FFC312VIP &8- &71 Vote Kasası"
      - "#FFC312VIP &8- &720 dk Fly"
      - "#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"
  3:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "#FFC312VIP &8- &71 Vote Kasası"
      - "#FFC312VIP &8- &720 dk Fly"
      - "#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"
  4:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "#FFC312VIP &8- &71 Vote Kasası"
      - "#FFC312VIP &8- &720 dk Fly"
      - "#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"
  5:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "#FFC312VIP &8- &71 Vote Kasası"
      - "#FFC312VIP &8- &720 dk Fly"
      - "#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"
  6:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "#FFC312VIP &8- &71 Vote Kasası"
      - "#FFC312VIP &8- &720 dk Fly"
      - "#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"
  7:
    display-name: "&6Gün #%day%" # gün numarası
    lore:
      - "&2Oyuncu &8- &716 Toprak"
      - "&#FFC312VIP &8- &71 Vote Kasası"
      - "&#FFC312VIP &8- &720 dk Fly"
      - "&#0be881Mega&fVIP &8- &7 Oylama 2"
      - "#12CBC4Ultra&fVIP &8- &7 Parlak 2"
      - "#F79F1FSpear&fVIP &8- &7 Oylama 2"
      - "#e84118Spear&fVIP+ &8- &7 Oylama 2"

title: "&8Günlük Ödül"